version: "3.9"

services:
  admin-ui:
    container_name: admin-ui
    build:
      context: ./apps/admin-ui
      target: dev
      additional_contexts:
        - repo=./

    volumes:
      - ./apps/admin-ui/src:/app/src
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin-ui.rule=Host(`admin.localhost.com`)"
      - "traefik.http.routers.admin-ui.entrypoints=web"
      - "traefik.http.services.admin-ui.loadbalancer.server.port=3000"
    networks:
      - blog-manager

  comment-microfrontend:
    container_name: comment-microfrontend
    build:
      context: ./apps/comment-microfrontend
      target: dev
      additional_contexts:
        - repo=./

    volumes:
      - ./apps/comment-microfrontend/src:/app/src
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.comment-microfrontend.rule=Host(`comment-mfe.localhost.com`)"
      - "traefik.http.routers.comment-microfrontend.entrypoints=web"
      - "traefik.http.services.comment-microfrontend.loadbalancer.server.port=3000"
    networks:
      - blog-manager

  comment-service:
    container_name: comment-service
    build:
      context: ./apps/comment-service
      target: dev
      additional_contexts:
        - repo=./
    volumes:
      - ./apps/comment-service/src:/app/src
    environment:
      - RABBIT_MQ_HOST=amqp://rabbitmq
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.comment-service.rule=Host(`comment-service.localhost.com`)"
      - "traefik.http.routers.comment-service.entrypoints=web"
      - "traefik.http.services.comment-service.loadbalancer.server.port=3000"
    networks:
      - blog-manager

  post-service:
    container_name: post-service
    build:
      context: ./apps/post-service
      target: dev
      additional_contexts:
        - repo=./
    volumes:
      - ./apps/post-service/src:/app/src
    environment:
      - RABBIT_MQ_HOST=amqp://rabbitmq
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.post-service.rule=Host(`post-service.localhost.com`)"
      - "traefik.http.routers.post-service.entrypoints=web"
      - "traefik.http.services.post-service.loadbalancer.server.port=3000"
    networks:
      - blog-manager

  blog-service:
    container_name: blog-service
    build:
      context: ./apps/blog-service
      target: dev
      additional_contexts:
        - repo=./
    volumes:
      - ./apps/blog-service/src:/app/src
      - static-posts:/tmp/static-posts
    environment:
      - RABBIT_MQ_HOST=amqp://rabbitmq
    depends_on:
      db:
        condition: service_healthy
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.blog-service.rule=Host(`blog-service.localhost.com`)"
    #   - "traefik.http.routers.blog-service.entrypoints=web"
    #   - "traefik.http.services.blog-service.loadbalancer.server.port=3000"
    networks:
      - blog-manager

  user-service:
    container_name: user-service
    build:
      context: ./apps/user-service
      target: dev
      additional_contexts:
        - repo=./

    volumes:
      - ./apps/user-service/src:/app/src
    environment:
      - RABBIT_MQ_HOST=amqp://rabbitmq
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user-service.rule=Host(`user-service.localhost.com`)"
      - "traefik.http.routers.user-service.entrypoints=web"
      - "traefik.http.services.user-service.loadbalancer.server.port=3000"
    networks:
      - blog-manager

  auth-service:
    container_name: auth-service
    build:
      context: ./apps/auth-service
      target: dev
      additional_contexts:
        - repo=./
    volumes:
      - ./apps/auth-service/src:/app/src
    environment:
      - RABBIT_MQ_HOST=amqp://rabbitmq
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-service.rule=Host(`auth-service.localhost.com`)"
      - "traefik.http.routers.auth-service.entrypoints=web"
      - "traefik.http.services.auth-service.loadbalancer.server.port=3000"
    networks:
      - blog-manager

  signup-service:
    container_name: signup-service
    build:
      context: ./apps/signup-service
      target: dev
      additional_contexts:
        - repo=./
    volumes:
      - ./apps/signup-service/src:/app/src
    environment:
      - RABBIT_MQ_HOST=amqp://rabbitmq
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.signup-service.rule=Host(`signup-service.localhost.com`)"
      - "traefik.http.routers.signup-service.entrypoints=web"
      - "traefik.http.services.signup-service.loadbalancer.server.port=3000"
    networks:
      - blog-manager

  db:
    container_name: db
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5s
    networks:
      - blog-manager

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 3s
      timeout: 30s
      retries: 3
    networks:
      - blog-manager

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - blog-manager

  httpd:
    container_name: httpd
    image: httpd
    volumes:
      - static-posts:/usr/local/apache2/htdocs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`blog.localhost.com`)"
      - "traefik.http.routers.blog.entrypoints=web"
      - "traefik.http.services.blog.loadbalancer.server.port=80"
    networks:
      - blog-manager

networks:
  blog-manager:

volumes:
  static-posts:
